---
- name: "Download Ubuntu"
  hosts: "localhost"
  gather_facts: no
  vars:
    cc_action: "download"
  roles:
    - { role: ubuntu }
- name: "Upload Ubuntu"
  hosts: "localhost"
  gather_facts: no
  vars:
    cc_action: "upload"
  roles:
    - { role: pve_ssh, when: cc_hypervisor == 'pve_ssh' }
- name: "Create VMs"
  hosts: "all"
  gather_facts: no
  serial: 1
  vars:
    cc_action: "create"
  roles:
    - { role: pve_ssh, when: cc_hypervisor == 'pve_ssh' }
- name: "Create VMs"
  hosts: "all"
  gather_facts: no
  vars:
    cc_action: "create"
  roles:
    - { role: vsphere, when: cc_hypervisor == 'vsphere' }