---
- name: "Delete VMs"
  hosts: "all"
  gather_facts: no
  vars_prompt:
  - name: "delete_cluster"
    prompt: "Do you want to delete this cluster (yes/no)?"
    private: no
  vars:
    cc_action: "delete"
  roles:
    - { role: hyperv_ssh, when: cc_hypervisor == 'hyperv_ssh' and (delete_cluster | bool) }
    - { role: pve_ssh, when: cc_hypervisor == 'pve_ssh' and (delete_cluster | bool) }
    - { role: vsphere, when: cc_hypervisor == 'vsphere' and (delete_cluster | bool) }