---
- hosts: all
  gather_facts: no
  vars_prompt:
  - name: delete_cluster
    prompt: "Do you want to delete the cluster (yes/no)?"
    private: no
  tasks:
  - name: Power off VM
    community.vmware.vmware_guest:
      hostname: "{{ external_vsphere_vcenter_ip }}"
      username: "{{ external_vsphere_user }}"
      password: "{{ external_vsphere_password }}"
      validate_certs: "{{ not external_vsphere_insecure }}"
      name: "{{ inventory_hostname }}"
      state: poweredoff
    delegate_to: localhost
    when: delete_cluster | bool
  - name: Delete VM
    community.vmware.vmware_guest:
      hostname: "{{ external_vsphere_vcenter_ip }}"
      username: "{{ external_vsphere_user }}"
      password: "{{ external_vsphere_password }}"
      validate_certs: "{{ not external_vsphere_insecure }}"
      name: "{{ inventory_hostname }}"
      state: absent
    delegate_to: localhost
    when: delete_cluster | bool