---
- name: "Power on VMs"
  hosts: "all"
  gather_facts: no
  vars:
    cc_action: "poweron"
  roles:
    - { role: hyperv_ssh, when: cc_hypervisor == 'hyperv_ssh' }
    - { role: pve_ssh, when: cc_hypervisor == 'pve_ssh' }
    - { role: vsphere, when: cc_hypervisor == 'vsphere' }