---
- name: "Power off VMs"
  hosts: "all"
  gather_facts: no
  vars:
    cc_action: "poweroff"
  roles:
    - { role: vsphere, when: cc_hypervisor == 'vsphere' }
    - { role: pve_ssh, when: cc_hypervisor == 'pve_ssh' }